name: awakeY zero
favicon: null
layout_spectrum: 0.4275
typography_spectrum: 0.42234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5cc9b2'
    - '#4b4b49'
    - '#000000'
    - '#7d7d7d'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
